apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-helloworld
  namespace: argocd
spec:
  destination:
    namespace: demo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: solutions/argocd/python-manifests
    repoURL: https://github.com/marymar34567/nd064_course_1
    targetRevision: HEAD
  syncPolicy: {}
